### ISSUE TITLE
Training Error

### ISSUE THREAD

**Issue by scoutys** [nie-lang/DeepRectangling#20]
当我使用DIR-D训练时，出现以下错误：
Traceback (most recent call last):
  File "train.py", line 81, in <module>
    train_data_dataset = train_data_loader(batch_size=batch_size)
  File "/home/zhangao/MVS/Image-Stitching/DeepRectangling/Codes/utils.py", line 22, in __call__
    length = data_info_list[0]['length']
IndexError: list index out of range

**Comment by nie-lang** [comment]
这是由于数据集没有正确读入，请检查数据集目录、位置等。
或查看下图输出，是否成功读入了input, mask, gt
![1679649259545](https://user-images.githubusercontent.com/54256137/227476595-fe60a73e-ea41-4f4e-8e35-dcc7196b5665.png)

**Comment by scoutys** [comment]
感谢您的回答！

**Comment by HSL1999** [comment]
你好！请问这个问题最终您怎么解决的呢？

**Comment by nut0813** [comment]
> 感谢您的回答！

请问您最后怎么排除的呢，现在我也遇到了这个问题，
#training dataset path
TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'

#testing dataset path
TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing
是需要改动这两个吗，

**Comment by HSL1999** [comment]
您的邮件已收到，祝您生活愉快！

**Comment by scoutys** [comment]
> > 感谢您的回答！
> 
> 请问您最后怎么排除的呢，现在我也遇到了这个问题， #training dataset path TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'
> 
> #testing dataset path TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing 是需要改动这两个吗，

是的，请确保路径目录的正确性，或是检查数据集文件是否完整。

**Comment by nut0813** [comment]
> > > 感谢您的回答！
> > 
> > 
> > 请问您最后怎么排除的呢，现在我也遇到了这个问题， #training dataset path TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'
> > #testing dataset path TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing 数据集路径 TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，
> 
> 是的，请确保路径目录的正确性，或是检查数据集文件是否完整。
感谢您的回复，请问可以添加我的微信吗Nut0107，部署过程中还有一点问题  希望您指教一下  如果可以的话有偿

**Comment by nut0813** [comment]
> > > 感谢您的回答！
> > 
> > 
> > 请问您最后怎么排除的呢，现在我也遇到了这个问题， #training dataset path TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'
> > #testing dataset path TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing 数据集路径 TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，
> 
> 是的，请确保路径目录的正确性，或是检查数据集文件是否完整。

真不好意思又打扰您了 请问这个test_folder 应当怎么设置呢  我是在inference的统计文件夹下建了一个data文件夹 ，下面那放了 training和testing两个 貌似这里只用到testing  并放置了几张拼接后的图像  所以对应的 测试路径为 TEST_FOLDER = '/data/testing'
但是仍然报出ist index out of range的错误 
期待您的回复

**Comment by scoutys** [comment]
> > > > 感谢您的回答！
> > > 
> > > 
> > > 请问您最后怎么排除的呢，现在我也遇到了这个问题， #training dataset path TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'
> > > #testing dataset path TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing 数据集路径 TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，
> > 
> > 
> > 是的，请确保路径目录的正确性，或是检查数据集文件是否完整。
> > 感谢您的回复，请问可以添加我的微信吗Nut0107，部署过程中还有一点问题  希望您指教一下  如果可以的话有偿

我的数据集设置路径是：data/DIR-D/testing、data/DIR-D/training，都位于根目录下，你可以尝试一下。

**Comment by scoutys** [comment]
#training dataset path
TRAIN_FOLDER = './data/DIR-D/training/'

#testing dataset path
TEST_FOLDER = './data/DIR-D/testing/'

#GPU index
GPU = '1'

#batch size for training
TRAIN_BATCH_SIZE = 4

#batch size for testing
TEST_BATCH_SIZE = 1

#num of iters
ITERATIONS = 100000

# checkpoints path
SNAPSHOT_DIR = "./checkpoints"

#sumary path
SUMMARY_DIR = "./summary"

# define the mesh resolution
GRID_W = 8
GRID_H = 6

我的constant.py配置文件如上

**Comment by nut0813** [comment]
> > > > > 感谢您的回答！
> > > > 
> > > > 
> > > > 请问您最后怎么排除的呢，现在我也遇到了这个问题， #training dataset path TRAIN_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/training'
> > > > #testing dataset path TEST_FOLDER = '/data/cylin/nl/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing 数据集路径 TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing dataset path TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，#testing 数据集路径 TEST_FOLDER = '/data/cylin/en/Data/DIR-D-fusion/testing 是需要改动这两个吗，
> > > 
> > > 
> > > 是的，请确保路径目录的正确性，或是检查数据集文件是否完整。
> > > 感谢您的回复，请问可以添加我的微信吗Nut0107，部署过程中还有一点问题  希望您指教一下  如果可以的话有偿
> 
> 我的数据集设置路径是：data/DIR-D/testing、data/DIR-D/training，都位于根目录下，你可以尝试一下。

谢谢您 我之前因为没把数据集放到正确位置 后来将数据集的路径修改为绝对路径就好了 谢谢您的回复

**Comment by khanonuvov** [comment]
Go to Codes/utils.py and find this line 'data_name = data.split('/')[-1]' and write this line below the given picture.



![image](https://github.com/nie-lang/DeepRectangling/assets/59321214/38c8c566-8ba5-44ec-83fb-c145687ad9fb)

**Comment by HSL1999** [comment]
您的邮件已收到，祝您生活愉快！
